### ISSUE TITLE
Release 1.4.1 crashes silently

### ISSUE THREAD

**Issue by rfuehrer** [gao-sun/eul#68] opened 2020-11-09 08:59 UTC
Version 1.4.1 crashes without warning when switching between the areas in the settings (excerpt; no idea which elements are relevant for error analysis; i filtered the console log for "eul").

Affected systems: MacBook Pro, iMac27, both with Catalina 10.15.7 

```
Acquiring assertion targeting executable<eul(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:146] with description <RBSAssertionDescriptor; frontmost:9324; ID: 307-146-480; target: 9324> attributes = {
    <RBSDomainAttribute: 0x7fa0afd27e60; domain: com.apple.launchservicesd; name: RoleUserInteractiveFocal; sourceEnvironment: 0x0>;
}

Assertion 307-146-480 (target:executable<eul(501)>) will be created as active

[executable<eul(501)>:9324] Ignoring jetsam update because this process is not memory-managed

Finished acquiring assertion 307-146-480 (target:executable<eul(501)>)

[executable<eul(501)>:9324] Set darwin role to: UserInteractiveFocal

Task <DF301F3B-3BB0-4DBB-960A-0451095CF219>.<4> resuming, QOS(0x21) Voucher (null)

Task <DF301F3B-3BB0-4DBB-960A-0451095CF219>.<4> summary for task success {transaction_duration_ms=0, response_status=200, cache_hit=1}

[executable<eul(501)>:9324] Ignoring GPU update because this process is not GPU managed

Task <DF301F3B-3BB0-4DBB-960A-0451095CF219>.<4> finished successfully

precondition failure: <private>

Connection removed: IOHIDEventSystemConnection uuid:9727EC1C-44A8-4241-A5BB-C01F1B948E23 pid:9324 process:eul type:Passive entitlements:0x0 caller:HIServices: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) state:0x1 events:0 mask:0x0

Connection removed: IOHIDEventSystemConnection uuid:045336F7-8B79-4ACB-890A-2BC6A0EE315D pid:9324 process:eul type:Passive entitlements:0x0 caller:HIToolbox: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) state:0x1 events:0 mask:0x0

[executable<eul(501)>:9324] Death sentinel fired!

Invalidating assertion 307-146-480 (target:executable<eul(501)>) from originator 146

-[PersistentAppsSupport applicationQuit:] | for app:eul, _appTrackingState = 2

Invalidating assertion 307-146-396 (target:executable<eul(501)>) from originator 146

defusing ticker tickerFatal having seen progress by flow for com.gaosun.eul, rxbytes 6050 duration 21.571 seconds started at time: Mon Nov  9 09:46:08 2020

Parsing corpse data for process eul [pid 9324]

Removing process: [executable<eul(501)>:9324]

Removing assertions for terminated process: [executable<eul(501)>:9324]

Sending event: com.apple.stability.crash {"appVersion":"1.4.1","bundleID":"com.gaosun.eul","exceptionType":13,"process":"eul","responsibleApp":"eul"}

Received event: com.apple.stability.crash {"appVersion":"1.4.1","bundleID":"com.gaosun.eul","exceptionType":13,"process":"eul","responsibleApp":"eul"}

Aggregated. Transform: StabilityCrashNumerator Dirty: 3 Event: com.apple.stability.crash {"appVersion":"1.4.1","bundleID":"com.gaosun.eul","exceptionType":13,"process":"eul","responsibleApp":"eul","timestamp":1604911593015960}

Aggregated. Transform: StabilityCrashNumerator2 Dirty: 1 Event: com.apple.stability.crash {"appVersion":"1.4.1","bundleID":"com.gaosun.eul","exceptionType":13,"process":"eul","responsibleApp":"eul","timestamp":1604911593015960}

Aggregated. Transform: StabilityCrashNumerator3 Dirty: 1 Event: com.apple.stability.crash {"appVersion":"1.4.1","bundleID":"com.gaosun.eul","exceptionType":13,"process":"eul","responsibleApp":"eul","timestamp":1604911593015960}

Handling an apps installed notification with bundle IDs (
    "com.gaosun.eul"
)
```

**Comment by someblu** [comment] 2020-11-09 09:30
I met the same crash when switching tabs in the settings UI. The dump files can be found here [eul_crash.zip](https://github.com/gao-sun/eul/files/5509427/eul_crash.zip)

**Comment by gao-sun** [comment] 2020-11-09 11:42
taking a look tonight

**Comment by gao-sun** [comment] 2020-11-09 14:16
@rfuehrer thanks for your info
@someblu thanks, super helpful. would you mind let me know how to export these crash files thus I can write up in issue template?

have to admit I laughed when I see the "precondition failure" keyword. it's a "classical" bug according to my experience when using SwiftUI in iOS and Google results ([link1](https://developer.apple.com/forums/thread/133958) [link2](https://developer.apple.com/forums/thread/129171)). which is caused by the mixing of `NavigationView` and `GeometryReader`.

get back to the point, the problem might be `HSplitView` since it's under the same section as `NavigationView` in [docs](https://developer.apple.com/documentation/swiftui/view-layout-and-presentation) (I know it sounds dumb but that's the best I can guess for now, cannot reproduce crash in Big Sur) so I replaced it with `HStack` in [v1.4.2](https://github.com/gao-sun/eul/releases/latest).

fingers crossed. let me know if the new version works.

**Comment by Metis77** [comment] 2020-11-09 14:27
still crashing for me. v1.4.2 MacOS 10.15.7

**Comment by gao-sun** [comment] 2020-11-09 14:30
@Metis77 thanks. I'll find a Catalina MacBook for debugging. give me few more days. stay tuned. cheers

**Comment by rfuehrer** [comment] 2020-11-09 14:41
same here: iMac27 and MacBook Pro with Catalina still crashing

**Comment by crownzdp** [comment] 2020-11-09 14:42
> @Metis77 thanks. I'll find a Catalina MacBook for debugging. give me few more days. stay tuned. cheers

is it ok in Big Sur?

**Comment by crownzdp** [comment] 2020-11-09 14:43
is it ok in Big Sur？

**Comment by gao-sun** [comment] 2020-11-09 14:45
> same here: iMac27 and MacBook Pro with Catalina still crashing

give me few more days for a debugging MacBook

> is it ok in Big Sur？

works for me in 13' and 15' MacBook Pro

**Comment by someblu** [comment] 2020-11-10 02:10
@gao-sun open `~/Library/Logs/DiagnosticReports/` and you'll find them right there. Or open`console.app` and click `Crash Reports`.

**Comment by someblu** [comment] 2020-11-10 02:18
@gao-sun still crashes, 16' MacBook Pro, MacOS 10.15.7 and Eul 1.4.2. Here is the latest dump file. [eul_2020-11-10-101439.crash.zip](https://github.com/gao-sun/eul/files/5514393/eul_2020-11-10-101439.crash.zip)

**Comment by gao-sun** [comment] 2020-11-10 13:29
@someblu will borrow a Catalina macbook for debugging. stay tuned

**Comment by gao-sun** [comment] 2020-11-11 16:07
please try [v1.4.3](https://github.com/gao-sun/eul/releases)

**Comment by someblu** [comment] 2020-11-12 02:37
tested on my macbook pro, it doesn't crash any more. I think it has been fixed.

**Comment by gao-sun** [comment] 2020-11-12 13:34
@rfuehrer would you mind to double check if this has been fixed in v1.4.3

**Comment by Metis77** [comment] 2020-11-12 13:51
no more crashes for me with 1.4.3

**Comment by rfuehrer** [comment] 2020-11-12 22:09
everything fine with 1.4.3 
- MacBook Pro Catalina 👍🏼 
- iMac27 Catalina 👍🏼

**Comment by gao-sun** [comment] 2020-11-13 03:52
you guys are amazing

**Closed by gao-sun** 2020-11-13 03:52 UTC
Labels: bug
