### ISSUE TITLE
在设置里面点击几下左边工具栏会闪退

### ISSUE THREAD

**Issue by crownzdp** [gao-sun/eul#60] opened 2020-11-07 13:26 UTC

**Comment by gao-sun** [comment] 2020-11-07 14:29
tried to click the left tabs multiple times but cannot reproduce. would you mind to provide your device and OS info?

**Comment by crownzdp** [comment] 2020-11-07 14:51
> tried to click the left tabs multiple times but cannot reproduce. would you mind to provide your device and OS info?
mbp 16inch - macOS 10.15.7

**Comment by crownzdp** [comment] 2020-11-07 14:58
this is gif : https://sm.ms/image/OM7sSuCRp4wnDcK

**Comment by gao-sun** [comment] 2020-11-08 03:44
taking a look

**Comment by reputati0n** [comment] 2020-11-09 10:21
version:1.4.1
my device: MBP 13 2020 macOS 10.15.7
the problem is still

**Comment by gao-sun** [comment] 2020-11-09 10:28
will take a look on Catalina tonight

**Comment by gao-sun** [comment] 2020-11-09 14:20
please try `v1.4.2`, closing it since duplicate. please track this issue in #68

**Closed by gao-sun** 2020-11-09 14:20 UTC
Labels: question
