### ISSUE TITLE
[bug]CPU flashing, light background

### ISSUE THREAD

**Issue by shutter-cp** [gao-sun/eul#128] opened 2020-12-15 07:34 UTC
os ：11.0.1
eul: v1.4.8
Light color wallpaper
![屏幕录制2020-12-15-15 28 35](https://user-images.githubusercontent.com/37921589/102184808-06f6b400-3eeb-11eb-93bf-e64786c619c5.gif)

**Comment by gao-sun** [comment] 2020-12-15 14:57
ah, interesting. will take a look soon

**Comment by gao-sun** [comment] 2020-12-28 16:38
could not reproduce on Big Sur + light theme but please try v1.5 for a potential try (changed gradient fill to solid color filling on path). let me know if it doesn't help.

**Comment by mmichon** [comment] 2020-12-29 02:17
v1.5 is still flashing for me, at least in dark mode (auto-set after sunset).

**Comment by krubenok** [comment] 2021-01-04 15:53
I'm also having this issue on 1.5 with Big Sur 11.2 Beta. It flashes much more quickly in light mode and when toggling to Dark Mode I can slow it down to be less distracting. 

Of note, I'm using an eGPU now and wasn't previously when I didn't have this issue. I wonder if that's a commonality?

**Comment by gao-sun** [comment] 2021-01-05 02:14
thanks for detailed feedback, not sure if it's an issue related to eGPU. I have 2 MacBooks running Big Sur (15' and 13') but cannot re-produce.
the good news is a friend of mine reported this issue as well and i will contact him to debug this soon

**Comment by gao-sun** [comment] 2021-01-05 02:16
quick update: reproduced in 15' MacBook, will try to take a look tonight!

**Comment by gao-sun** [comment] 2021-01-11 05:36
please try v1.5.1, should be fixed

**Comment by mmichon** [comment] 2021-01-14 02:27
Looks like it's fixed for me on Big Sur 11.1 on an M1 MBA

**Comment by gao-sun** [comment] 2021-01-17 15:28
@shutter-cp @krubenok does it work in v1.5.1?

**Comment by shutter-cp** [comment] 2021-01-19 09:22
> @ shutter-cp @krubenok在v1.5.1中有效吗？

yes effect thank you

**Comment by gao-sun** [comment] 2021-01-20 02:59
glad to see it works, you guys are awesome

**Closed by gao-sun** 2021-01-20 02:59 UTC
Labels: bug
